src/Entity/Course.php
<?php

namespace App\Entity;

use App\Repository\CourseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CourseRepository::class)
 */
class Course
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $niveau;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $Public;

    /**
     * @ORM\OneToMany(targetEntity=Child::class, mappedBy="coursValide")
     */
    private $membre;

    /**
     * @ORM\Column(type="integer")
     */
    private $maxMember;

    /**
     * @ORM\OneToMany(targetEntity=Child::class, mappedBy="cours")
     */
    private $members;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $heure;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $fin;

    /**
     * @ORM\OneToMany(targetEntity=Absence::class, mappedBy="courseName")
     */
    private $absences;

    public function __construct()
    {
        $this->members = new ArrayCollection();
        $this->absences = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getNiveau(): ?string
    {
        return $this->niveau;
    }

    public function setNiveau(string $niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getPublic(): ?string
    {
        return $this->Public;
    }

    public function setPublic(string $Public): self
    {
        $this->Public = $Public;

        return $this;
    }

    public function getMaxMember(): ?string
    {
        return $this->maxMember;
    }

    public function setMaxMember(string $maxMember): self
    {
        $this->maxMember = $maxMember;

        return $this;
    }

    /**
     * @return Collection|Child[]
     */
    public function getMembers(): Collection
    {
        return $this->members;
    }

    public function addMember(Child $member): self
    {
        if (!$this->members->contains($member)) {
            $this->members[] = $member;
            $member->setCours($this);
        }

        return $this;
    }

    public function removeMember(Child $member): self
    {
        if ($this->members->removeElement($member)) {
            // set the owning side to null (unless already changed)
            if ($member->getCours() === $this) {
                $member->setCours(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNom();
    }

    public function getHeure(): ?string
    {
        return $this->heure;
    }

    public function setHeure(string $heure): self
    {
        $this->heure = $heure;

        return $this;
    }

    public function getFin(): ?string
    {
        return $this->fin;
    }

    public function setFin(string $fin): self
    {
        $this->fin = $fin;

        return $this;
    }

    /**
     * @return Collection|Absence[]
     */
    public function getAbsences(): Collection
    {
        return $this->absences;
    }

    public function addAbsence(Absence $absence): self
    {
        if (!$this->absences->contains($absence)) {
            $this->absences[] = $absence;
            $absence->setCourseName($this);
        }

        return $this;
    }

    public function removeAbsence(Absence $absence): self
    {
        if ($this->absences->removeElement($absence)) {
            // set the owning side to null (unless already changed)
            if ($absence->getCourseName() === $this) {
                $absence->setCourseName(null);
            }
        }

        return $this;
    }
}

src/Form/CourseType.php
<?php

namespace App\Form;

use App\Entity\Course;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CourseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Nom')
            ->add('date')
            ->add('niveau')
            ->add('Public')
            ->add('maxMember')
            ->add('heure')
            ->add('fin');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Course::class,
        ]);
    }
}

src/Controller/CourseController.php
<?php

namespace App\Controller;

use App\Entity\Course;
use App\Form\CourseType;
use App\Repository\CourseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;


/**
 * @Route("/course")
 */
class CourseController extends AbstractController
{
    /**
     * @Route("/", name="course_index", methods={"GET"})
     */
    public function index(CourseRepository $courseRepository): Response
    {
        return $this->render('course/index.html.twig', [
            'courses' => $courseRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="course_new", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request): Response
    {
        $course = new Course();
        $form = $this->createForm(CourseType::class, $course);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($course);
            $entityManager->flush();

            return $this->redirectToRoute('course_management');
        }

        return $this->render('course/new.html.twig', [
            'course' => $course,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/schedule", name="schedule", methods={"GET", "POST"})
     * @IsGranted("ROLE_USER")
     */
    public function schedule(CourseRepository $repository): Response
    {
        $cours = $repository->findAll();

        return $this->render('course/schedule.html.twig', ['cours' => $cours]);
    }

    /**
     * @Route("/{id}", name="course_show", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function show(Course $course): Response
    {
        return $this->render('course/show.html.twig', [
            'course' => $course,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="course_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Course $course): Response
    {
        $form = $this->createForm(CourseType::class, $course);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('course_management');
        }

        return $this->render('course/edit.html.twig', [
            'course' => $course,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="course_delete", methods={"DELETE"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Course $course): Response
    {
        if ($this->isCsrfTokenValid('delete' . $course->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($course);
            $entityManager->flush();
        }

        return $this->redirectToRoute('course_index');
    }
}

templates/course/_delete_form.html.twig
<form method="post" action="{{ path('course_delete', {'id': course.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_method" value="DELETE">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ course.id) }}">
	<button class="btn">Supprimer</button>
</form>

templates/course/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/course/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Course
{% endblock %}

{% block body %}
	<h1>Edit Course</h1>

	{{ include('course/_form.html.twig', {'button_label': 'Update'}) }}

	<a href="{{ path('course_management') }}">back to list</a>

	{{ include('course/_delete_form.html.twig') }}
{% endblock %}

templates/course/index.html.twig
{% block body %}

	<div class="cours">
		<div class="absenceContenu">
			<table class="table">
				<thead>
					<tr>
						<th>Nom</th>
						<th>Date</th>
						<th>Heure de début</th>
						<th>Heure de fin</th>
						<th>Niveau</th>
						<th>Public</th>
						<th>Membres maximum</th>
						<th>Membres</th>
						<th>actions</th>
					</tr>
				</thead>
				<tbody>
					{% for course in courses %}
						<tr>
							<td>{{ course.Nom }}</td>
							<td>{{ course.date }}</td>
							<td>{{ course.heure }}</td>
							<td>{{ course.fin }}</td>
							<td>{{ course.niveau }}</td>
							<td>{{ course.Public }}</td>
							<td>{{course.maxMember}}</td>
							<td>
								{% for member in course.members %}
									{{member.nom}}
									{{member.prenom}}
								{% endfor %}
							</td>
							<td>
								<a href="{{ path('course_show', {'id': course.id}) }}">Voir</a>
								<a href="{{ path('course_edit', {'id': course.id}) }}">Editer</a>
							</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="6">Pas de cours</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
	<div class="absencePic">
		<a href="{{ path('course_new') }}"><img src="/pictures/new.png"></a>
	</div>
{% endblock %}

templates/course/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau cours
{% endblock %}

{% block body %}
	<h1>Créer un nouveau cours</h1>
	<div class="formContact">
		<div class="contenuFormContact">
			{{ form_start(form) }}
			Nom du cours:
			<div class="champFormContact">{{form_widget(form.Nom)}}</div>
			Jour:
			<div class="champFormContact">{{form_widget(form.date)}}</div>
			Niveau:
			<div class="champFormContact">{{form_widget(form.niveau)}}</div>
			Public visé:
			<div class="champFormContact">{{form_widget(form.Public)}}</div>
			Nombre maximum de membre
			<div class="champFormContact">{{form_widget(form.maxMember)}}</div>
			Heure de début:
			<div class="champFormContact">{{form_widget(form.heure)}}</div>
			Heure de fin:
			<div class="champFormContact">{{form_widget(form.fin)}}</div>
			<button class="btn">{{ button_label|default('Save') }}</button>
			{{ form_end(form) }}
		</div>
	</div>

	<div class="back">
		<a href="{{ path('course_management') }}">
			<img src="/pictures/back.PNG">
		</a>
	</div>
{% endblock %}

templates/course/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Course
{% endblock %}

{% block body %}
	<h1>Course</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Nom</th>
				<td>{{ course.Nom }}</td>
			</tr>
			<tr>
				<th>Date</th>
				<td>{{ course.date }}</td>
			</tr>
			<tr>
				<th>Heure de début</th>
				<td>{{ course.heure }}</td>
			</tr>
			<tr>
				<th>Heure de fin</th>
				<td>{{ course.fin }}</td>
			</tr>
			<tr>
				<th>Niveau</th>
				<td>{{ course.niveau }}</td>
			</tr>
			<tr>
				<th>Public</th>
				<td>{{ course.Public }}</td>
			</tr>
			<tr>
				<th>Membres
				</th>
				<td>
					{% for member in course.members %}
						{{member.nom}}
						{{member.prenom}}
					{% endfor %}
				</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('course_management') }}">back to list</a>

	<a href="{{ path('course_edit', {'id': course.id}) }}">edit</a>

	<a href="{{ path('absence_new_admin') }}">Un membre est absent</a>

	{{ include('course/_delete_form.html.twig') }}
{% endblock %}